### ISSUE TITLE
support native-tls?

### ISSUE THREAD

**Issue by timzaak** [GunnarMorrigan/mqrstt#14]
~~just like: https://github.com/seanmonstar/reqwest/blob/master/Cargo.toml~~

~~because some weired crates only support  openssl.~~

The example :https://github.com/tokio-rs/tls/blob/master/tokio-native-tls/examples/download-rust-lang.rs

cargo.toml

mqrstt = "0.2.1"
tokio-native-tls = "0.3.1"
async-trait = "0.1.68"

```rust
            let cx = tokio_native_tls::native_tls::TlsConnector::builder().build()?;
            let cx = tokio_native_tls::TlsConnector::from(cx);
            
            let stream = tokio::net::TcpStream::connect((host, port)).await?;
            
            let connection = cx.connect(host, stream).await?;

            network.connect(connection,&mut mqtt_wrapper).await?;
```

**Comment by GunnarMorrigan** [comment]
He, thanks for using my crate and taking the time to open this issue :). 

I would expect it to work out of the box. As it likely uses the same traits. Have you gotten it to work? 

Let me know because I wouldn't mind introducing support if it is not present.
