### ISSUE TITLE
sample code not working 

### ISSUE THREAD

**Issue by harshakhmk** [GunnarMorrigan/mqrstt#18]
Hi, I tried out synchronous sample example, but getting an error
```
thread main panicked at src/main.rs
Called result::unwrap() on an err value : custom {kind : uncategorised, error: "failed to lookup address information:name or service not known"}

**Comment by GunnarMorrigan** [comment]
Hi,

I will post a working example here.
Are you using tls or not?
And version 0.2.2?

**Comment by GunnarMorrigan** [comment]
Hi if you check out the main branch you can find a working TCP sync example [here](https://github.com/GunnarMorrigan/mqrstt/tree/main/examples/sync_tcp_v0.2.2)

**Comment by harshakhmk** [comment]
Hi missed the address and port, that is what causing the issue
I was specifically looking for examples that have publish and subscribe examples

**Comment by GunnarMorrigan** [comment]
The example linked above does a subscribe and publishes messages as a response to incoming pings.
Usually, I subscribe to the needed topics when receiving a ConnAck.

Does the example work for you or are you trying to figure something else out?

If you could describe what you would like to achieve in more detail I could help you further.
